### ISSUE TITLE
problem encountered at the beginning of the training：ValueError

### ISSUE THREAD

**Issue by helcpp** [kwea123/ngp_pl#11]
Hello. It's an amazing job!

cuda11.7
wsl+ubuntu20.04
gtx1080

The problem is described as follows：

~/code/ngp_pl$ python train.py --root_dir /home/gzx/datasets/Lego/ --exp_name Lego
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: logs/Lego
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_setup_hook
    self._call_lightning_module_hook("setup", stage=fn)
  File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "train.py", line 67, in setup
    self.train_dataset = dataset(split=hparams.split, **kwargs)
  File "/home/gzx/code/ngp_pl/datasets/nsvf.py", line 43, in __init__
    K = np.loadtxt(os.path.join(root_dir, 'intrinsics.txt'),
  File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1301, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/gzx/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
ValueError: the number of columns changed from 4 to 3 at row 2; use `usecols` to select a subset and avoid this error

I don't know why this is happening and would like to get your help.

**Comment by kwea123** [comment]
Hi, can you keep the original folder structure? i.e. keep the `Synthetic_NeRF` folder etc. Because I check the folder name here
https://github.com/kwea123/ngp_pl/blob/a7329b465a5a0c75b886913d371907811c9ac7d8/datasets/nsvf.py#L26
in order to check which format to read.

Please tell me if it works on your system, thanks!

**Comment by helcpp** [comment]
I tried your method and the code works fine! I'll see the results in a moment. This is so exciting. 
Thank you very much.

**Comment by kwea123** [comment]
Can you add `--no_save_test` and try again? By default it loads all images to RAM, so if your memory is insufficient it causes OOM and killed.

**Comment by kwea123** [comment]
I suspect it's because of the warning
```
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
```

Can you change `rgbs` to `rgbs.contiguous()` at that line? If other variables have the same error, do the same thing (add `.contiguous()`) and try

**Comment by kwea123** [comment]
Thanks for confirming that it works for GPU with compute compatibility < 75.

An easy fix of high memory consumption will be to load one image at a time instead of all images once. It can be done by yourselves according to your use. Good luck extending this work!
