### ISSUE TITLE
ImportError: anaconda3/envs/ngp_pl/lib/python3.8/site-packages/vren.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb

### ISSUE THREAD

**Issue by khayamgondal** [kwea123/ngp_pl#111]
When I run the benchmark, it crashes with following error. I did uninstall and reinstalled vren but problem presists.

```
khayam@LT-KANJAM:~/nerf/ngp_pl$ python train.py --root_dir ../nerf_data/TruckandTemple/Truck/ --exp_name Truck --downsample 0.5 --no_save_test --num_epochs 20 --batch_size 16384 --lr 2e-2 --eval_lpips
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from models.networks import NGP
  File "/home/khayam/nerf/ngp_pl/models/networks.py", line 4, in <module>
    import vren
ImportError: /home/khayam/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/vren.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
```

**Comment by modoartwork** [comment]
Tell me about the environmental composition

What were the messages when you built and installed vren?

It may be related versions of ubuntu, gcc, cuda, pybind, cmake ... etc.

It certainly doesn't seem to be a problem with the libraries this repository provides.

**Comment by ThreeBoxWithCode** [comment]
> 
Hello, may I ask how you installed vren? I tried “pip install vren”, but the message "ERROR: No matching distribution found for vren" was displayed.

**Comment by ThreeBoxWithCode** [comment]
Hello, may I ask how you installed vren? I tried pip install vren, but the message "ERROR: No matching distribution found for vren" was displayed.

**Comment by rap64** [comment]
I had the same problem, how did you solve it?

**Comment by modoartwork** [comment]
> I had the same problem, how did you solve it?

run 'pip install models/csrc/' with cuda 11.3 with gcc-9 g++-9

**Comment by rap64** [comment]
> 



> > 我有同样的问题，你是怎么解决的？
> 
> 使用 CUDA 11.3 和 GCC-9 g++-9 运行“pip install models/csrc/”

I did this, but still showed this error

**Comment by modoartwork** [comment]
try this

git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

cd models/csrc && python setup.py install

**Comment by rap64** [comment]
> try this
> 
> git clone https://github.com/NVIDIA/apex cd apex pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> 
> cd models/csrc && python setup.py install

Sorry, I replied late, I reconfigured the environment and then found that I could not successfully install the apex cuda extension

**Comment by AanchalChugh** [comment]
I am getting this error: /anaconda3/envs/ngp_pl/lib/python3.8/site-packages/vren-2.0-py3.8-linux-x86_64.egg/vren.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE. Have followed quite a lot of potential solutions but does not work at all
