### ISSUE TITLE
Optimize extrinsics error

### ISSUE THREAD

**Issue by Xiaxia1997** [kwea123/ngp_pl#43]
The experimental training options optimize_ext crushed in my project. When optimizing extrinsics, the shape of self.dR[batch['img_idxs']] is [batchsize, 3] for training step and [3] for testing. However, the code to compute  `dR = axisangle_to_R(self.dR[batch['img_idxs']])` is the same for training and testing step. I'm trying to solve this problem, but didn't work now. Have you ever test optimize_ext ? 
The detailed error info is as follows:
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 266, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 255, in on_advance_end
    self._run_validation()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 311, in _run_validation
    self.val_loop.run()
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 128, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 226, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "train.py", line 199, in validation_step
    results = self(batch, split='test')
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "train.py", line 90, in forward
    dR = axisangle_to_R(self.dR[batch['img_idxs']])
  File "/home/user/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/x00586938/ngp_pl-master/datasets/ray_utils.py", line 84, in axisangle_to_R
    zero = torch.zeros_like(v[:, :1]) # (B, 1)
IndexError: too many indices for tensor of dimension 1

**Comment by Xiaxia1997** [comment]
I've solved it by expand the tensor to [1,3].

**Comment by kwea123** [comment]
Thank you, I'll find time to debug

**Comment by Xiaxia1997** [comment]
Need to add some info. The dR dT should be added only in the training process, the right way may be:
        if self.hparams.optimize_ext and split == 'train':
            dR = axisangle_to_R(self.dR[batch['img_idxs']])
            poses[..., :3] = dR @ poses[..., :3]
            dT = self.dT[batch['img_idxs']]
            poses[..., 3] += dT

**Comment by kwea123** [comment]
I haven't found time to fix, but the `dR dT` should be applied in testing to in case `split==trainval` (using all images to train and test on some of them).

**Comment by Xiaxia1997** [comment]
Thanks for your rely, but in my project, I add some noise to my GT pose for training, and use GT pose to test. So the dR dT should be remove during test process. 
Moreover, not all test images are included in training process, so we cannot get all dR dT. Then, if we want to generate the **novel view**,  we need to ignore the unknown dR dT and suppose the pose to generate is the GT pose.

**Comment by kwea123** [comment]
fixed
