### ISSUE TITLE
RuntimeError: Tensors of type TensorImpl do not have strides

### ISSUE THREAD

**Issue by yyashpatel** [kwea123/ngp_pl#68]
Hi Kwea !

could you help me with this error !

python train.py --root_dir ./nerf_llff_data/fern --dataset_name colmap
GridEncoding: Nmin=16 b=1.31951 F=2 T=2^19 L=16
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Loading 17 train images ...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:03<00:00,  4.71it/s]
Loading 3 test images ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  4.61it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Missing logger folder: logs/colmap/exp
Epoch 0:   0%|                                                                                                 | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 277, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1314, in _run_train
    self.fit_loop.run()
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    lightning_module.optimizer_step(
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1651, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 164, in step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in optimizer_step
    self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 85, in optimizer_step
    closure_result = closure()
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 142, in closure
    step_output = self._step_fn()
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 435, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 216, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 213, in training_step
    return self.model.training_step(*args, **kwargs)
  File "train.py", line 162, in training_step
    self.model.update_density_grid(0.01*MAX_SAMPLES/3**0.5,
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yash/Documents/ngp_pl/models/networks.py", line 256, in update_density_grid
    density_grid_tmp[c, indices] = self.density(xyzs_w)
  File "/home/yash/Documents/ngp_pl/models/networks.py", line 104, in density
    h = self.xyz_encoder(x)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yash/anaconda3/envs/NeRF_env/lib/python3.8/site-packages/tinycudann/modules.py", line 122, in forward
    self.params.to(_torch_precision(self.native_tcnn_module.param_precision())).contiguous(),
RuntimeError: Tensors of type TensorImpl do not have strides

**Comment by kwea123** [comment]
I have no idea where this error comes from. Can you try the command I post in another issue #70 ?

**Comment by letian-zhang** [comment]
I have same problem when I run python train.py --root_dir .\datasets\Synthetic_NeRF\Lego --exp_name Lego.
How to solve this problem.
