### ISSUE TITLE
Error about --val_only

### ISSUE THREAD

**Issue by cv-lab-x** [kwea123/ngp_pl#77]
hi, thanks for your great work! i got some errors when i just add --val_only and ckpath 

export ROOT_DIR=./360_v2
export DOWNSAMPLE=0.25 # to avoid OOM
python train.py \
    --root_dir $ROOT_DIR/garden --dataset_name colmap \
    --exp_name garden --downsample $DOWNSAMPLE  \
    --num_epochs 20 --scale 16.0 --eval_lpips --val_only --ckpt_path "./ckpts/colmap/garden/epoch=19_slim.ckpt"

got error
Restoring states from the checkpoint path at /data/x00480977/projects/nvvps/ngp_pl/ckpts/colmap/garden/epoch=19_slim.ckpt
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/root/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1179, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1141, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/root/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 179, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/root/miniconda3/envs/ngp_pl/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 319, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
KeyError: 'state_dict'

pytorch-lightning       1.7.7
torch                   1.12.0
python 3.8.13

looking forward for your reply, thanks
@kwea123

**Comment by kwea123** [comment]
Hi, for `--val_only` the `ckpt_path` need to be ` "./ckpts/colmap/garden/epoch=19.ckpt"` (without slim)
