### ISSUE TITLE
RuntimeError: Tensors of type TensorImpl do not have strides

### ISSUE THREAD

**Issue by letian-zhang** [kwea123/ngp_pl#88]
I have a error "RuntimeError: Tensors of type TensorImpl do not have strides" when I run the code python train.py --root_dir .\datasets\Synthetic_NeRF\Lego --exp_name Lego.
Please help me to solve the problem.
cuda=11.3
pytorch=1.21.1+cu113

(ngp_pl) D:\ngp_pl\ngp_pl>python train.py --root_dir .\datasets\Synthetic_NeRF\Lego --exp_name Lego
GridEncoding: Nmin=16 b=1.31951 F=2 T=2^19 L=16
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: logs/nsvf\Lego
Loading 100 train images ...
100it [00:04, 21.17it/s]
Loading 200 test images ...
200it [00:08, 23.37it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Training: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1166, in _run
    results = self._run_stage()
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\loops\loop.py", line 195, in run
    self.on_run_start(*args, **kwargs)
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 223, in on_run_start
    self.trainer._call_lightning_module_hook("on_train_start")
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "train.py", line 155, in on_train_start
    self.model.mark_invisible_cells(self.train_dataset.K.to(self.device),
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\ngp_pl\ngp_pl\models\networks.py", line 213, in mark_invisible_cells
    cells = self.get_all_cells()
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\ngp_pl\ngp_pl\models\networks.py", line 164, in get_all_cells
    indices = vren.morton3D(self.grid_coords).long()
RuntimeError: Tensors of type TensorImpl do not have strides

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 276, in <module>
    trainer.fit(system, ckpt_path=hparams.ckpt_path)
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 664, in _call_and_handle_interrupt
    self._teardown()
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1229, in _teardown
    self.strategy.teardown()
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 476, in teardown
    self.lightning_module.cpu()
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 141, in cpu
    return super().cpu()
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\torch\nn\modules\module.py", line 738, in cpu
    return self._apply(lambda t: t.cpu())
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\torch\nn\modules\module.py", line 738, in <lambda>
    return self._apply(lambda t: t.cpu())
RuntimeError: Tensors of type TensorImpl do not have strides

**Comment by letian-zhang** [comment]
Finally, I solve this problem by downgrade PyTorch from 1.12.1 to 1.11.0.

**Comment by kwea123** [comment]
Thank you, I will add this in readme.
