### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by letian-zhang** [kwea123/ngp_pl#90]
Hi, when I run the command below, there is a MemoryError. Please help me to solve the problem.
GPU:1080 TI 11GB
Cuda: 11.3
Pytorch 1.11.0

(ngp_pl) D:\ngp_pl\ngp_pl>python train.py --root_dir .\datasets\Synthetic_NeRF\Lego --exp_name Lego --batch_size 1024 --downsample 0.25
GridEncoding: Nmin=16 b=1.31951 F=2 T=2^19 L=16
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: logs/nsvf\Lego
Loading 100 train images ...
100it [00:04, 22.78it/s]
Loading 200 test images ...
200it [00:07, 25.74it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Epoch 0:   0%|                                                                                | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\envs\ngp_pl\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\anaconda3\envs\ngp_pl\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\anaconda3\envs\ngp_pl\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\anaconda3\envs\ngp_pl\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\anaconda3\envs\ngp_pl\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\anaconda3\envs\ngp_pl\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\anaconda3\envs\ngp_pl\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ngp_pl\ngp_pl\train.py", line 34, in <module>
    from pytorch_lightning.plugins import DDPPlugin
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\callbacks\pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\core\__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\core\module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\loggers\__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\pytorch_lightning\loggers\tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\anaconda3\envs\ngp_pl\lib\site-packages\torch\utils\tensorboard\__init__.py", line 10, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 934, in get_code
  File "<frozen importlib._bootstrap_external>", line 1033, in get_data
MemoryError

**Comment by hanbiao3906** [comment]
> 

You can open virtual memory on your computer to solve the problem

**Comment by letian-zhang** [comment]
Finally, I solved this problem by moving the instant-ngp out from the PyTorch-lighting and writing the training frame by myself.
